### ISSUE TITLE
move_to函数不能正确使用

### ISSUE THREAD

**Issue by 80491636** [beijixiaohu/CH9329_COMM#3]
这里的值无论是正数还是负数都报错。  
  def mouseClick(self,x,y):
        self.mouse.move_to(-100, -100)
        self.mouse.click()  # 单击左键

报错信息：
Exception in thread Thread-4:
Traceback (most recent call last):
  File "E:\ProjectFiles\python\python3.7\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\res\utils\MainLoop.py", line 88, in run
    comControl.mouseClick(dx,dy)
  File "E:\res\com\ComControl.py", line 33, in mouseClick
    self.mouse.move_to(-100, -100)
  File "E:\ProjectFiles\python\python3.7\lib\site-packages\ch9329Comm\mouse.py", line 294, in move_to
    corrected_x = dest_x * (1 / correction_factor)
ZeroDivisionError: division by zero

**Comment by beijixiaohu** [comment]
从报错来看，是校正值 correction_factor 为零，造成了除数为零的错误
你可以尝试删除 `information.json` 文件重新生成
